function eventsBrowserWindow(mainFig, analyzedEvntsBrowserTbl)

% create figure for events browser
scF = 0.5;
scrRes = get(0,'ScreenSize');
hf_evntBrowser = figure('Tag','CaEventsBrowser',...
    'Name','all analyzed events browser',...
    'Visible','on',...
    'OuterPosition',[floor((scrRes(3)-scrRes(3)*scF)/2) ...
    scrRes(4)*0.2 ...
    scrRes(3)*scF ...
    scrRes(4)*0.8]);
set(hf_evntBrowser,'Units','Normalized')

dx = 0.07;
dy = 0.07;
p_W = 1-2*dx;
p_H = 0.2;
a_H = (1 - 3*dy - p_H)/2;
a_W = (1 - 3*dx)/2;

% set up axes to show  individual calcium events
% image axes
ha_img = axes(hf_evntBrowser, 'Units','normalized', ...
    'Position',[dx 1-a_H-dy a_W*1.25 a_H]);
% x-profile axes
ha_xProf = axes(hf_evntBrowser, 'Units','normalized', ...
    'Position',[ha_img.Position(1)+ha_img.Position(3)+dx+dx/2 ...
    1-a_H-dy ...
    a_W*0.75 a_H]);
% t-profile axes
ha_tProf = axes(hf_evntBrowser, 'Units','normalized', ...
    'Position',[dx ...
    ha_img.Position(2)-dy-ha_img.Position(4) ...
    ha_img.Position(3) a_H]);
% text with parameters of analyzed event
h_txt_params = uicontrol('Style','text', 'Parent',hf_evntBrowser, ...
    'Units','normalized', 'FontUnits','normalized', 'FontSize',0.1, ...
    'Position', [ha_xProf.Position(1) ...
    ha_xProf.Position(2)-dy-ha_xProf.Position(4) ha_xProf.Position(3) a_H],...
    'FontWeight','bold', 'HorizontalAlignment','center', ...
    'String',{'----','----','----','----'}); 

% add panel with slider to choose event and possibility to refit it
hpSelEvent = uipanel('Title','select event', ...
    'Parent',hf_evntBrowser, 'Units','normalized',...
    'Position',[dx ha_tProf.Position(2)-dy-p_H p_W p_H],...
    'Visible','on', 'FontUnits','normalized',...
    'FontSize',0.125, 'FontWeight','bold');
h_txt_evntSld = uicontrol('Style','text',...
    'Parent',hpSelEvent, 'Units','normalized', ...
    'Position',[0.05 0.85 0.9 0.15],...
    'FontUnits','normalized', 'FontSize',0.75, 'FontWeight','bold',...
    'HorizontalAlignment','center', 'String','------');
% set up slider 
sldMin = 1;
% n events
sldMax = height(analyzedEvntsBrowserTbl); 

sldStep = 1/(sldMax-sldMin);
if sldStep>=1, sldStep=1; end

sld_evnts = uicontrol('Style','slider','Parent',hpSelEvent, ...
    'FontUnits','normalized', 'Min',1, 'Max',sldMax, 'Value',1, ...
    'SliderStep',[sldStep sldStep],...
    'Units','normalized', 'Position',[0.05 0.65 0.9 0.15],...
    'Callback',{@showSelectedEventInBrowser, hf_evntBrowser, mainFig}, ...
    'Enable','on');
% if there is only single event
if sldStep == 1 && sldMin==sldMax
    set(sld_evnts,'Enable','off')
end

% add panel to reanalyze current event
hp_reFit = uipanel('Title','re-fit event', ...
    'Parent',hpSelEvent, 'Units','normalized',...
    'Position',[0.3 0.01 0.4 0.6], ...
    'FontUnits','normalized', 'FontWeight','bold',...
    'FontSize',0.2, 'FontAngle','italic');
uicontrol('Style','text',...
    'Parent',hp_reFit, 'Units','normalized',...
    'Position',[0.01 0.5 0.54 0.4], ...
    'String','span of loess smoothing (ms):', ...
    'FontUnits','normalized', 'FontSize',0.45, ...
    'FontWeight','normal');
h_smooth_reFit = uicontrol('Style','edit', 'String','50',...
    'Parent',hp_reFit, 'Units','normalized', ...
    'FontUnits','normalized', 'FontSize',0.5,...
    'Position',[0.55 0.5 0.15 0.4]);
uicontrol('Style','text', ...
    'FontUnits','normalized',...
    'Parent',hp_reFit, 'Units','normalized', 'FontSize',0.4,...
    'Position',[0.01 0.01 0.54 0.45],...
    'String','bs detection sensitivity (0-max, 100-min):',...
    'TooltipString','sensitivity for baseline estimation when fitting spark rise');
h_bsDet_reFit = uicontrol('Style','edit', 'String','75',...
    'FontUnits','normalized', 'FontSize',0.5,...
    'Parent',hp_reFit, 'Units','normalized', ...
    'Position', [0.55 0.05 0.15 0.4], ...
    'TooltipString','sensitivity for baseline estimation when fitting spark rise');
uicontrol('Style', 'pushbutton',...
    'String','re-fit',...
    'FontUnits','normalized', 'FontSize',0.4, ...
    'FontWeight','bold',...
    'Parent',hp_reFit, 'Units','normalized', ...
    'Position',[0.725 0.1 0.25 0.8],...
    'Callback',{@refitSelectedEvent, mainFig, hf_evntBrowser}, ...
    'Enable','on');

% save data and handles
hObjs.h_smooth_reFit = h_smooth_reFit;
hObjs.h_bsDet_reFit = h_bsDet_reFit;
hObjs.ha_img = ha_img;
hObjs.ha_xProf = ha_xProf;
hObjs.ha_tProf = ha_tProf;
hObjs.sld_evnts = sld_evnts;
hObjs.h_txt_evntSld = h_txt_evntSld;
hObjs.h_txt_params = h_txt_params;
setappdata(hf_evntBrowser, 'hObjs', hObjs)

% call slider function to show first event
showSelectedEventInBrowser(sld_evnts, [], hf_evntBrowser, mainFig)

end