function MainWindowSparksAndProfiles(analysisType)
%% create main figure and axes   
mainFig = figure('Name',sprintf('%s',analysisType), ...
    'units','normalized', 'outerposition',[0 0.05 1 0.95]);
set(mainFig, 'PaperPositionMode','auto', ...
             'PaperOrientation','landscape', ...
             'PaperType','A4', ...
             'Tag','mainFig');
% create axes
ax_img = axes('Parent',mainFig);
set(ax_img, 'Position',[0.03 0.72 0.94 0.25], 'Tag','img')
% set(get(ax_img,'Xlabel'),'String','t (ms)')
set(ax_img,'XTick',[],'FontSize',14)
set(get(ax_img,'Ylabel'),'String','x (pixels)','FontWeight','bold')
ax_img.Toolbar.Visible = 'off';

% set up scale
ax_sc_img = axes('Parent',mainFig); % invisible axes
set(ax_sc_img, 'Visible','off', ...
    'Position',[0.975 0.5225 0.005 0.125], 'Tag','scale img');
% Switch off autoscaling.
set(ax_sc_img, 'Xlim',[0, 1], 'YLim',[0, 1]);
line([0.5 0.5],[0,1], ...
    'Parent',ax_sc_img, 'LineWidth',4, 'Color','k')
h_txt_scale_img = text('Parent',ax_sc_img, ...
    'Position',[1 0.5], ...
    'String',[sprintf('%0.2f',0),' \mum'],...
    'FontSize',16, 'FontWeight','bold', 'Rotation',90,...
    'HorizontalAlignment','center', 'VerticalAlignment','cap');

% profile axes
ax_prof = axes('Parent',mainFig, ...
    'units','normalized', 'PickableParts','all', 'Tag','profile');
set(ax_prof, 'Position',[0.03 0.26 0.94 0.19], ...
    'YGrid','on', 'FontSize',14)
set(get(ax_prof,'Xlabel'),'String','t (ms)','FontWeight','bold')
set(get(ax_prof,'Ylabel'),'String','Fluorescence (F)','FontWeight','bold')
ax_prof.Toolbar.Visible = 'off';

% setup axes positions based on analysis type
switch analysisType
    case 'spark detection'
        ax_img.Position = [0.03 0.5 0.94 0.47];
        ax_prof.Position = [0.03 0.26 0.94 0.23];
        % axes links
        hlink1 = linkprop([ax_img,ax_prof],'XLim');
        hlink2 = [];
    otherwise % repetitive sparks profiles
        % add axes to show selected repetitive sparks
        ax_img_sparks = axes('Parent',mainFig);
        set(ax_img_sparks, 'Position',[0.03 0.46 0.94 0.25])
        ax_img_sparks.Toolbar.Visible = 'off';
        % set(get(ax_img_sparks,'Xlabel'),'String','t (ms)')
        set(ax_img_sparks, 'XTick',[], ...
            'YDir','reverse', 'FontSize',14, 'Tag','img_sparks')
        set(get(ax_img_sparks,'Ylabel'), ...
            'String','x (pixels)', 'FontWeight','bold')
        % add scale bar for sparks axes
        ax_sc_sparks = axes('Parent',mainFig); % invisible axes
        set(ax_sc_sparks, 'Visible','off', ...
            'Position',[0.975 ...
            ax_img_sparks.Position(2)+ax_img_sparks.Position(4)/4 ...
            0.005 ax_img_sparks.Position(4)/2], ...
            'Tag','scale sparks');
        % Switch off autoscaling.
        set(ax_sc_sparks, 'Xlim',[0, 1], 'YLim',[0, 1]);
        line([0.5 0.5],[0,1], ...
            'Parent',ax_sc_sparks, 'LineWidth',4, 'Color','k')
        h_txt_scale_sparks = text('Parent',ax_sc_sparks, ...
            'Position',[1 0.5], ...
            'String',[sprintf('%0.2f',0),' \mum'],...
            'FontSize',16, 'FontWeight','bold', 'Rotation',90,...
            'HorizontalAlignment','center', 'VerticalAlignment','cap');
        % axes links
        hlink1 = linkprop([ax_img,ax_img_sparks,ax_prof],'XLim');
        hlink2 = [];
        %linkaxes([ax_img,ax_img_sparks,ax_img_orig],'xy')
        %linkaxes([ax_img,ax_img_sparks,ax_prof,ax_img_orig],'x')
        hObjs.ax_img_sparks = ax_img_sparks;
        hObjs.h_txt_scale_sparks = h_txt_scale_sparks;
end
% set up position for scale of image axes 
ax_sc_img.Position = [0.975 ax_img.Position(2)+ax_img.Position(4)/4 ...
    0.005 ax_img.Position(4)/2];

hObjs.mainFig = mainFig;
hObjs.ax_img = ax_img;
hObjs.h_txt_scale_img = h_txt_scale_img;
hObjs.ax_prof = ax_prof;
hObjs.hlink1 = hlink1;
hObjs.hlink2 = hlink2;


%% text to show image path and name and channels assignment 
txt_name_img = uicontrol('Style','text',...
    'Parent',mainFig,'Units','normalized','Position', [0.25 0.980 0.51 0.02],...
    'FontUnits','normalized','FontSize',0.6,'FontWeight','bold',...
    'HorizontalAlignment','left','String','image name');

% individual channels assignment 
uicontrol('Style','text',...
    'Parent',mainFig,'Units','normalized','Position', [0.01 0.980 0.03 0.02],...
    'FontUnits','normalized','FontSize',0.75,'FontWeight','bold',...
    'HorizontalAlignment','left','String','fluo ch:');
popUpMenuChFluo = uicontrol('Style','popup',...
    'Parent',mainFig,'Units','normalized','Position', [0.04 0.980 0.05 0.02],...
    'FontUnits','normalized','FontSize',0.75,'Tag','mainImgFluoCh',...
    'String',{'ch #1','ch #2','none'},'Callback', {@setImgChannel,mainFig});

uicontrol('Style','text',...
    'Parent',mainFig,'Units','normalized','Position', [0.1 0.980 0.04 0.02],...
    'FontUnits','normalized','FontSize',0.75,'FontWeight','bold',...
    'HorizontalAlignment','left','String','trans ch:');
popUpMenuChTrans = uicontrol('Style','popup',...
    'Parent',mainFig,'Units','normalized','Position', [0.14 0.980 0.05 0.02],...
    'FontUnits','normalized','FontSize',0.75,'Tag','mainImgTransCh',...
    'String',{'ch #1','ch #2','none'},'Callback', {@setImgChannel,mainFig});

% axes to show trans channel
h_ax_transCh = axes('Parent',mainFig);
set(h_ax_transCh, 'Position',[0.19 0.975 0.05 0.0209], ...
    'XTick',[], 'YTick',[], 'FontSize',8)
h_ax_transCh.Toolbar.Visible = 'off';

hObjs.txt_name_img = txt_name_img;
hObjs.h_ax_transCh = h_ax_transCh;
hObjs.popUpMenuChFluo = popUpMenuChFluo;
hObjs.popUpMenuChTrans = popUpMenuChTrans;


%% create slider when image is too big in time direction
h_bg_sld = uibuttongroup('Visible','on', 'Parent',mainFig, ...
    'Units','normalized', 'Position',[0.815 0.975 0.125 0.025],...
    'SelectionChangedFcn',{@bg_sld_selection});                   
% Create radio buttons in the button group.
h_b1 = uicontrol(h_bg_sld,'Style','radiobutton', ...
    'Units','normalized',...
    'String','whole image', 'FontUnits','normalized', ...
    'FontSize',0.75, 'Position',[0.05 0.05 0.55 0.9],...
    'HandleVisibility','off');
h_b2 = uicontrol(h_bg_sld,'Style','radiobutton', ...
    'Units','normalized', 'String','#s part', ...
    'FontUnits','normalized', 'FontSize',0.75,...
    'Position',[0.6 0.05 0.45 0.9],...
    'HandleVisibility','off');

h_edit_imgSld_w = uicontrol('Style','edit', 'String','5',...
    'FontUnits','normalized', 'FontSize',0.75,...
    'Parent',mainFig, 'Units','normalized',...
    'Position',[0.94 0.975 0.02 0.025],...
    'Callback', {@bg_sld_selection});
uicontrol('Style','text', 'Parent',mainFig, ...
    'Units','normalized',...
    'Position', [0.96 0.975 0.01 0.025],...
    'FontUnits','normalized', 'FontSize',0.75, 'String','s', ...
    'HorizontalAlignment','center');

h_img_sld = uicontrol('Style','slider', ...
    'Parent',mainFig, 'FontUnits','normalized',...
    'Min',1, 'Max',100, 'Value',1, 'Units','normalized',...
    'Position',[0.03 ax_img.Position(2)-0.01 0.94 0.01], ...
    'BackgroundColor',[0.7 0.7 0.7],...
    'Callback','', 'Enable','off'); %{@imgShow_slider}

hObjs.h_bg_sld = h_bg_sld;
hObjs.h_b1_sld = h_b1;
hObjs.h_b2_sld = h_b2;
hObjs.h_edit_imgSld_w = h_edit_imgSld_w;
hObjs.h_img_sld = h_img_sld;


%% open image
h_pb_open = uicontrol('Style', 'pushbutton',...
    'String','<html> <p align="center"> open <br> image <html>',...
    'FontUnits','normalized', 'FontSize',0.225, 'FontWeight','bold',...
    'Parent',mainFig, 'Units','normalized', ...
    'Position',[0.01 0.12 0.05 0.1],...
    'Callback',{@openImg, mainFig}, ...
    'Enable','on');
hObjs.h_pb_open = h_pb_open;


%% pixel sizes panel
hp_pxSz = uipanel('Title','pixel sizes:','Parent',mainFig,...
    'Position',[0.01 0.01 0.05 0.1],'FontUnits','normalized',...
    'FontSize',0.15,'FontWeight','bold');

uicontrol('Style','text', 'Parent',hp_pxSz, 'Units','normalized',...
        'Position',[0.01 0.55 0.39 0.4], ...
        'String',{'x', '(µm)'}, ...
        'FontUnits','normalized','FontSize',0.4);       
h_edit_pxSzX = uicontrol('Style','edit', 'String','1',...
        'Parent',hp_pxSz,'Units','normalized', ...
        'Position', [0.45 0.55 0.5 0.4], 'Tag','pxSzX',...
        'FontUnits','normalized','FontSize',0.5, ...
        'Callback', {@setPxSzManually, mainFig});
uicontrol('Style','text', 'Parent',hp_pxSz, 'Units','normalized',...
        'Position',[0.01 0.05 0.39 0.4], ...
        'String',{'t', '(ms)'}, ...
        'FontUnits','normalized','FontSize',0.4);       
h_edit_pxSzT = uicontrol('Style','edit', 'String','1',...
        'Parent',hp_pxSz,'Units','normalized', ...
        'Position', [0.45 0.05 0.5 0.4], 'Tag','pxSzT',...
        'FontUnits','normalized','FontSize',0.5, ...
        'Callback', {@setPxSzManually, mainFig});
hObjs.h_edit_pxSzX = h_edit_pxSzX;
hObjs.h_edit_pxSzT = h_edit_pxSzT;


%% animal/experiment notes
hpA = uipanel('Title','animal & notes','Parent',mainFig,...
    'Position',[0.065 0.07 0.1 0.15],...
    'Visible','on', 'Units','normalized', ...
    'FontUnits','normalized',...
    'FontSize',0.14, 'FontWeight','bold');

popUpMenuAnimal = uicontrol('Style','popup',...
    'Parent',hpA, 'Units','normalized', ...
    'Position',[0 0.85 1 0.15],...
    'FontUnits','normalized', 'FontSize',0.9, ...
    'Tag','popUpMenuAnimal',...
    'String',{'wt',...
              'PA-RFP RyR', ...
              'wt (S2030A littermate)',...
              'wt (R420Q littermate)',...
              'S2030A',...
              'S2808A/14A',...                         
              'R420Q (homozygous)',...
              'R420Q (heterozygous)', ...
              'IP3R/tTA', ...
              'wt/tTA', ...
              'unknown'});

ScSz = get(0,'ScreenSize');
h_table_notes = uitable( ...
    'Data',{'ctrl'; ...
            'animal #: '; ...
            '1.8 mM CaCl2 tyrode'; ...
            'field stim.: 30 s, 1 Hz (0.5 ms, 30 V)'; ...
            'loading: 2 uM Cal520 AM, 60 min (RT)';''},...
    'ColumnEditable',true,...
    'ColumnName',{'<HTML> <font size="4"> <b> notes </b> </HTML>'},...
    'ColumnWidth',{hpA.Position(3)*0.8*ScSz(3)}, 'Parent',hpA,...
    'Units','normalized', 'Position',[0 0 1 0.8],...
    'FontUnits','normalized', 'FontSize',0.14);

hObjs.popUpMenuAnimal = popUpMenuAnimal;
hObjs.h_table_notes = h_table_notes;


%% set ROI to cropp image
h_pb_crop = uicontrol('Style', 'pushbutton',...
    'String','<html> <p align="center"> set ROI to crop <html>',...
    'FontUnits','normalized', 'FontSize',0.4,...
    'Parent',mainFig, 'Units','normalized', ...
    'Position',[0.065 0.01 0.1 0.05],...
    'Callback',{@cropImg, mainFig}, 'Enable','on');
hObjs.h_pb_crop = h_pb_crop;


%% panel for blank
hp3 = uipanel('Title','blank', 'Parent',mainFig, ...
    'Position',[0.17 0.12 0.09 0.1],...
    'Visible','on', 'Units','normalized', 'FontUnits','normalized',...
    'FontSize',0.21, 'FontWeight','bold');

h_push_BlankROI = uicontrol('Style', 'pushbutton', ...
    'String','set ROI for blank',...
    'FontUnits','normalized', 'Parent',hp3, ...
    'Units','normalized', 'FontSize',0.5,...
    'Position',[0.1 0.5 0.8 0.45], ...
    'Callback',{@setBlankROI, mainFig});

h_edit_Blank = uicontrol('Style', 'edit', 'String','nan',...
    'FontUnits','normalized', 'Parent',hp3, 'Units','normalized',...
    'FontSize',0.6, 'Position',[0.6 0.075 0.35 0.4],...
    'Callback',{@calculateBlank, mainFig});
    
h_pb_GetBlank = uicontrol('Style', 'pushbutton',...
    'String','cell', 'FontUnits','normalized', 'FontSize',0.5,...
    'Parent',hp3, 'Units','normalized', ...
    'Position',[0.05 0.05 0.5 0.45],...
    'Callback',{@getBlankXYimg, mainFig}, 'Enable','on');

hObjs.h_edit_Blank = h_edit_Blank;
hObjs.h_push_BlankROI = h_push_BlankROI;
hObjs.h_pb_GetBlank = h_pb_GetBlank;


%% panel normalization 
hp5 = uipanel('Title','self-ratio', 'Parent',mainFig, ...
    'Position',[0.17 0.01 0.09 0.1],...
    'FontUnits','normalized', 'FontSize',0.21, 'FontWeight','bold');

h_pb_norm = uicontrol('Style', 'pushbutton', 'FontUnits','normalized',...
    'String','normalize data', 'FontSize',0.5,...
    'Parent',hp5, 'Units','normalized', ...
    'Position',[0.05 0.52 0.9 0.45],...
    'Callback',{@norm_data, mainFig});

switch analysisType
    case 'spark detection'
        h_pb_norm.Enable = 'off';
    otherwise
        h_pb_norm.Enable = 'on';
end

h_pb_undo_norm = uicontrol('Style', 'pushbutton', ...
    'String','start over',...
    'FontUnits','normalized', 'FontSize',0.5,...
    'Parent',hp5, 'Units','normalized', ...
    'Position',[0.05 0.03 0.9 0.45],...
    'Callback',{@undo_norm, mainFig});

hObjs.h_pb_norm = h_pb_norm;
hObjs.h_pb_undo_norm = h_pb_undo_norm;


%% panel for spark detection 
hp_SD = uipanel('Title','sparks detection', 'Parent',mainFig,...
    'Position',[0.265 0.01 0.245 0.21], 'FontUnits','normalized',...
    'FontSize',0.1, 'FontWeight','bold');

hp_crit = uipanel('Title','criteria', 'Parent',hp_SD,...
    'Position',[0.01 0.01 0.3 0.95], 'FontUnits','normalized',...
    'FontSize',0.1, 'FontAngle','italic');

txt1 = uicontrol('Style','text', 'Parent',hp_crit, ...
    'Units','normalized',...
    'Position', [0.05 0.85 0.55 0.125], ...
    'String','FWHM (px)',...
    'TooltipString',['<html> The full-width-at-half-maximum (FWHM) of the Gaussian spatial filter. <br>',...
    'This should be <= the FWHM of a typical spark, defined in terms of pixels. <br> (Default = 8) <html>']);
h_edit_fFWHM = uicontrol('Style','edit', 'String','8',...
    'Parent',hp_crit, 'Units','normalized', ...
    'Position',[0.65 0.825 0.3 0.15],...
    'TooltipString',['<html> The full-width-at-half-maximum (FWHM) of the Gaussian spatial filter. <br>',...
    'This should be <= the FWHM of a typical spark, defined in terms of pixels. <br> (Default = 8) <html>'],...
    'Callback',{@setCriteriaSparkDetection, mainFig});

txt2 = uicontrol('Style','text',...
    'Parent',hp_crit, 'Units','normalized',...
    'Position',[0.05 0.65 0.55 0.125], 'String','smooth_Iter',...
    'TooltipString',['<html> The number of smoothing iterations to apply along the temporal dimension. <br>',...
    'Higher values suppress noise, but excessively high values cause sparks to be suppressed too. <br> (Default = 3) <html>']);
h_edit_smoothIter = uicontrol('Style', 'edit', 'String','3',...
    'Parent',hp_crit, 'Units','normalized', ...
    'Position',[0.65 0.625 0.3 0.15],...
    'TooltipString',['<html> The number of smoothing iterations to apply along the temporal dimension. <br>',...
    'Higher values suppress noise, but excessively high values cause sparks to be suppressed too. <br> (Default = 3) <html>'],...
    'Callback', {@setCriteriaSparkDetection, mainFig});

txt3 = uicontrol('Style','text',...
    'Parent',hp_crit, 'Units','normalized',...
    'Position', [0.05 0.45 0.55 0.125], 'String','base_Iter',...
    'TooltipString',['<html> The number of smoothing iterations to apply for estimating the baseline. <br>',...
    'It must be greater than SMOOTH_ITER. <br>',...
    'If sparks occur from a constant baseline, high values can be used <br>',...
    '(effectively resulting in the mean fluorescence of the row being used to estimate the baseline). <br>',...
    'Because the filter size increases dramatically, this should not be higher than about 10. <br>',...
    'For quickly varying baselines, smaller values are required to avoid undesirable detections. (Default = 5) <html>']);
h_edit_baseIter = uicontrol('Style','edit', 'String','5',...
    'Parent',hp_crit, 'Units','normalized', ...
    'Position',[0.65 0.425 0.3 0.15],...
    'TooltipString',['<html> The number of smoothing iterations to apply for estimating the baseline. <br>',...
    'It must be greater than SMOOTH_ITER. <br>',...
    'If sparks occur from a constant baseline, high values can be used <br>',...
    '(effectively resulting in the mean fluorescence of the row being used to estimate the baseline). <br>',...
    'Because the filter size increases dramatically, this should not be higher than about 10. <br>',...
    'For quickly varying baselines, smaller values are required to avoid undesirable detections. (Default = 5) <html>'],...
    'Callback',{@setCriteriaSparkDetection, mainFig});

txt4 = uicontrol('Style','text',...
    'Parent',hp_crit, 'Units','normalized',...
    'Position',[0.05 0.25 0.55 0.125], 'String','treshold',...
    'TooltipString','Threshold value, defined in terms of noise standard deviations. (Default = 5)');
h_edit_tresh = uicontrol('Style', 'edit', 'String','5',...
    'Parent',hp_crit, 'Units','normalized', ...
    'Position',[0.65 0.225 0.3 0.15],...
    'TooltipString','Threshold value, defined in terms of noise standard deviations. (Default = 5)',...
    'Callback',{@setCriteriaSparkDetection, mainFig});

txt5 = uicontrol('Style','text',...
    'Parent',hp_crit, 'Units','normalized',...
    'Position',[0.05 0.05 0.55 0.125], 'String','expFactor',...
    'TooltipString',['<html> EXPANSION_FACTOR - A value between 0 and 1 that determines the size of detected spark regions. <br>',...
    'Lower values give larger regions. A value of 1 means that sparks are detected by simply thresholding the processed image at treshold. <br>',...
    'Such regions might be too small to contain the peaks of events. (Default = 0.5) <html>']);
h_edit_expFactor = uicontrol('Style', 'edit', 'String','0.5',...
    'Parent',hp_crit, 'Units','normalized', ...
    'Position',[0.65 0.025 0.3 0.15],...
    'TooltipString',['<html> EXPANSION_FACTOR - A value between 0 and 1 that determines the size of detected spark regions. <br>',...
    'Lower values give larger regions. A value of 1 means that sparks are detected by simply thresholding the processed image at treshold. <br>',...
    'Such regions might be too small to contain the peaks of events. (Default = 0.5) <html>'],...
    'Callback',{@setCriteriaSparkDetection, mainFig});

editArray = {h_edit_fFWHM, h_edit_smoothIter, h_edit_baseIter, ...
    h_edit_tresh, h_edit_expFactor};
txtArray = {txt1, txt2, txt3, txt4, txt5};
cellfun(@(x) set(x,'FontUnits','normalized', 'FontSize',0.75, ...
    'FontWeight','normal'),txtArray)
cellfun(@(x) set(x,'FontUnits','normalized', 'FontSize',0.75, ...
    'FontWeight','normal'),editArray)

y_d = 0.15;
h_push_DetectSparks = uicontrol('Style', 'pushbutton',...
    'String','<html> <p align="center"> find sparks & calculate spF <br> & normalize image <html>',...
    'FontUnits','normalized', 'FontSize',0.25, ...
    'FontWeight','bold', 'Parent',hp_SD,...
    'Units','normalized', 'Position', [0.325 0.7-y_d 0.4 0.3],...
    'Callback',{@eventsDetection, mainFig, 'new'}, ...
    'Enable','on', 'Tag','findEvents');
  
txt_SpF = uicontrol('Style','text', 'FontUnits','normalized',...
    'Parent',hp_SD, 'Units','normalized', 'FontSize',0.7,...
    'Position',[0.325 0.55-y_d 0.4 0.125], ...
    'String',['# sp*100',char(956),'m-1*s-1'],...
    'ForegroundColor','r');

check_visRect = uicontrol('Style', 'checkbox', 'Parent',hp_SD,...
    'FontUnits','normalized', 'Value',1, ...
    'Units','normalized', 'FontSize',0.75,...
    'String','show detected sparks rect', ...
    'Position',[0.325 0.445-y_d 0.4 0.1],...
    'Callback',{@checkRectVisibility, mainFig});

check_doBsFit = uicontrol('Style', 'checkbox', 'Parent',hp_SD,...
    'FontUnits','normalized', 'Value',0, ...
    'Units','normalized', 'FontSize',0.75,...
    'String','baseline polynomial fit', ...o
    'Position',[0.325 0.335-y_d 0.4 0.1],...
    'Callback','');

check_watershed = uicontrol('Style', 'checkbox', ...
    'Parent',hp_SD, 'FontUnits','normalized', ...
    'Value',1, 'Units','normalized', 'FontSize',0.75,...
    'String','watershed transform', ...
    'Position',[0.325 0.225-y_d 0.4 0.1],...
    'TooltipString','separate merged events');

% slider for sensitivity of watershed transform
% txt_spDet = uicontrol('Style','text', 'FontUnits','normalized',...
%     'Parent',hp_SD, 'Units','normalized', 'FontSize',0.7,...
%     'Position',[0.325 0.125 0.4 0.1], ...
%     'String','watershed sensitivity 50%', 'Enable','on');
% 
% sld_spDet = uicontrol('Style', 'slider', 'Parent',hp_SD, ...
%     'FontUnits','normalized',...
%     'Min',1, 'Max',100, 'Value',50, 'Units','normalized',...
%     'Position',[0.325 0.01 0.4 0.1],...
%     'Callback',{@spDet_slider, mainFig}, 'Enable','on');

uicontrol('Style','text',...
        'Parent',hp_SD, 'Units','normalized',...
        'Position',[0.75 0.8 0.225 0.2], ...
        'String','event ROI duration (ms)',...
        'FontUnits','normalized', 'FontSize',0.375);
uicontrol('Style','text',...
        'Parent',hp_SD, 'Units','normalized',...
        'Position',[0.75 0.7 0.1 0.1], 'String','min:',...
        'FontUnits','normalized', 'FontSize',0.75);
uicontrol('Style','text',...
        'Parent',hp_SD, 'Units','normalized',...
        'Position',[0.875 0.7 0.1 0.1], 'String','max:',...
        'FontUnits','normalized', 'FontSize',0.75);
h_edit_MinDurSpark = uicontrol('Style', 'edit', ...
        'String','10',...
        'Parent',hp_SD, 'Units','normalized', ...
        'Position',[0.75 0.55 0.1 0.15],...
        'FontUnits','normalized', 'FontSize',0.5,...
        'Callback',{@setCriteriaSparkDetection,mainFig});
h_edit_MaxDurSpark = uicontrol('Style', 'edit', 'String','inf',...
        'Parent',hp_SD, 'Units','normalized', ...
        'Position',[0.875 0.55 0.1 0.15],...
        'FontUnits','normalized', 'FontSize',0.5,...
        'Callback',{@setCriteriaSparkDetection,mainFig});

uicontrol('Style','text',...
        'Parent',hp_SD, 'Units','normalized',...
        'Position',[0.75 0.3 0.225 0.2],...
        'FontUnits','normalized', 'FontSize',0.375,...
        'String',['min width of spark', [' (',char(956),'m)']]);
uicontrol('Style','text',...
        'Parent',hp_SD, 'Units','normalized',...
        'Position', [0.75 0.2 0.1 0.1], 'String','min:',...
        'FontUnits','normalized', 'FontSize',0.75);
uicontrol('Style','text',...
        'Parent',hp_SD, 'Units','normalized',...
        'Position',[0.875 0.2 0.1 0.1], 'String','max:',...
        'FontUnits','normalized', 'FontSize',0.75);
h_edit_MinWidthSpark = uicontrol('Style', 'edit', 'String','0.5',...
        'Parent',hp_SD, 'Units','normalized', ...
        'Position',[0.75 0.05 0.1 0.15],...
        'FontUnits','normalized', 'FontSize',0.5,...
        'Callback',{@setCriteriaSparkDetection,mainFig});
h_edit_MaxWidthSpark = uicontrol('Style', 'edit', 'String','inf',...
        'Parent',hp_SD, 'Units','normalized', ...
        'Position',[0.875 0.05 0.1 0.15],...
        'FontUnits','normalized', 'FontSize',0.5,...
        'Callback',{@setCriteriaSparkDetection,mainFig});

hObjs.h_edit_fFWHM = h_edit_fFWHM;
hObjs.h_edit_smoothIter = h_edit_smoothIter;
hObjs.h_edit_baseIter = h_edit_baseIter;
hObjs.h_edit_tresh = h_edit_tresh;
hObjs.h_edit_expFactor = h_edit_expFactor;

hObjs.h_push_sparks = h_push_DetectSparks;
hObjs.txt_SpF = txt_SpF;
hObjs.check_visRect = check_visRect;
hObjs.check_watershed = check_watershed;
hObjs.check_doBsFit = check_doBsFit;
%hObjs.txt_spDet = txt_spDet;
%hObjs.sld_spDet = sld_spDet;

hObjs.h_edit_MinDurSpark = h_edit_MinDurSpark;
hObjs.h_edit_MaxDurSpark = h_edit_MaxDurSpark;
hObjs.h_edit_MinWidthSpark = h_edit_MinWidthSpark;
hObjs.h_edit_MaxWidthSpark = h_edit_MaxWidthSpark;


%% panel for analysis
switch analysisType
    
    case 'spark detection'
        %%%%%%%%%%%%%% panel for spark analysis %%%%%%%%%%%%%%%
        %%
        hp_SA = uipanel('Title','analyze detected sparks', ...
            'Parent',mainFig, 'Units','normalized', ...
            'Position',[0.515 0.01 0.3 0.21],...
            'FontUnits','normalized', 'FontSize',0.1, ...
            'FontWeight','bold');
        
        % criteria
        hp_cSR = uipanel('Title','selection criteria:', ...
            'Parent',hp_SA, 'Units','normalized',...
            'Position',[0.01 0.01 0.325 0.95], 'FontUnits','normalized',...
            'FontSize',0.1, 'FontAngle','italic');
        
        txt_noise = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized', ...
            'Position',[0 0.8 0.6 0.2],...
            'String',{'spAmpl >';'2*noise (F/F0)'},...
            'TooltipString','amplitude of spark is higher than noise estimated as SD of normalized image without sparks area');
        
        h_edit_noise = uicontrol('Style', 'edit', 'String','0.2',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position',[0.6 0.8 0.35 0.175], ...
            'Callback',{@sparkParamsFiltering,mainFig},...
            'TooltipString','amplitude of spark is higher than noise estimated as SD of normalizde image without sparks area');
        
        txt_spFDHM = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position',[0 0.55 0.6 0.2], 'String',{'spFDHM >','(ms)'},...
            'TooltipString','FDHM of spark is higher than set value');
        
        h_edit_spFDHM = uicontrol('Style', 'edit', 'String','5',...
            'Parent',hp_cSR, 'Units','normalized', ...
            'Position',[0.6 0.55 0.35 0.175],...
            'TooltipString','FDHM of spark is higher than set value',...
            'Callback',{@sparkParamsFiltering,mainFig});
        
        txt_spFWHM = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position', [0 0.3 0.6 0.2], ...
            'String',{'spFWHM >';['(',char(956),'m)']},...
            'TooltipString','FWHM of spark is higher than set value');
        
        h_edit_spFWHM = uicontrol('Style', 'edit', 'String','0.25',...
            'Parent',hp_cSR, 'Units','normalized', ...
            'Position',[0.6 0.3 0.35 0.175],...
            'TooltipString','FWHM of spark is higher than set value',...
            'Callback',{@sparkParamsFiltering,mainFig});
        
        h_smooth_txt = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position',[0 0.05 0.6 0.2], ...
            'String',{'span of smoothing:';'(ms)\loess'});
        
        h_smooth_edit = uicontrol('Style','edit', 'String','50',...
            'Parent',hp_cSR, 'Units','normalized', ...
            'Position',[0.6 0.05 0.35 0.175]);
        
        editArray2 = {h_smooth_edit, h_edit_spFDHM, ...
            h_edit_spFWHM,h_edit_noise};
        txtArray2 = {txt_noise, txt_spFDHM, txt_spFWHM, h_smooth_txt};
        cellfun(@(x) set(x,'FontUnits','normalized', 'FontSize',0.375, ...
            'FontWeight','normal'),txtArray2)
        cellfun(@(x) set(x,'FontUnits','normalized', 'FontSize',0.65, ...
            'FontWeight','normal'),editArray2)
        % save handles
        hObjs.h_edit_noise = h_edit_noise;
        hObjs.h_edit_spFDHM = h_edit_spFDHM;
        hObjs.h_edit_spFWHM = h_edit_spFWHM;
        hObjs.h_smooth_edit = h_smooth_edit;
     
        % method for spark parameters calculation, create two radio buttons in the button group
        calcSpParamMethodRBgroup = uibuttongroup(hp_SA, ...
            'Units','normalized',...
            'Title','spark params calc method:', ...
            'FontUnits','normalized',...
            'FontSize',0.186, 'FontWeight','normal', 'FontAngle','italic',...
            'Position',[0.35 0.45 0.375 0.51]);
      
        rb1 = uicontrol('Style','radiobutton', ...
            'Parent',calcSpParamMethodRBgroup,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.7,...
            'String','max crossing profiles', ...
            'Position',[0.05 0.7 0.9 0.3]);
        
        rb2 = uicontrol('Style','radiobutton', ...
            'Parent',calcSpParamMethodRBgroup,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.7,...
            'String','2D gaussian fit', ...
            'Position',[0.05 0.35 0.9 0.3], 'Enable','on');
        
        rb3 = uicontrol('Style','radiobutton', ...
            'Parent',calcSpParamMethodRBgroup,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.7,...
            'String','estimate from event img', ...
            'Position',[0.05 0.01 0.9 0.3], 'Enable','on');
        
        check_showEventsFigs = uicontrol('Style', 'checkbox', ...
            'Parent',hp_SA, 'FontUnits','normalized', ...
            'Value',0, 'Units','normalized', 'FontSize',0.8,...
            'String','show individual events', ...
            'Position',[0.35 0.3 0.3 0.1],...
            'Callback',{@analysisOpt,mainFig});
        
        h_bsDet_txt = uicontrol('Style','text', ...
            'FontUnits','normalized',...
            'Parent',hp_SA, 'Units','normalized', 'FontSize',0.22,...
            'Position',[0.35 0.01 0.25 0.25],...
            'String',{'baseline detection';'sensitivity';'0-max, 100-min'},...
            'TooltipString','sensitivity for baseline estimation when fitting spark rise');
        
        h_bsDet_edit = uicontrol('Style','edit', 'String','75',...
            'FontUnits','normalized', 'FontSize',0.55,...
            'Parent',hp_SA, 'Units','normalized', ...
            'Position', [0.575 0.05 0.1 0.17], ...
            'Callback',{@profileROI,mainFig},...
            'TooltipString','sensitivity for baseline estimation when fitting spark rise');
        
        % color code for rectangles of detected sparks
        uicontrol('Style','text', 'FontUnits','normalized',...
            'Parent',hp_SA, 'Units','normalized', 'FontSize',0.375,...
            'Position',[0.75 0.85 0.225 0.15],...
            'String',{'red = accepted';'black = not accepted'});
        
        h_pb_sparksAnalysis = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> analyze <br> sparks <html>',...
            'FontUnits','normalized', 'FontSize',0.3, ...
            'Parent',hp_SA, 'FontWeight','bold',...
            'Units','normalized', 'Position',[0.75 0.5 0.225 0.35],...
            'Callback',{@detectedSparksAnalysis,mainFig}, ...
            'Enable','on', 'Tag','calcParamsOfEvents');

        check_useNormalizedImg = uicontrol('Style', 'checkbox', ...
            'Parent',hp_SA, 'FontUnits','normalized', ...
            'Value',1, 'Units','normalized', 'FontSize',0.8,...
            'String','in normalized image', ...
            'Position',[0.725 0.35 0.275 0.1],...
            'Callback','');
        
        uicontrol('Style','text', 'FontUnits','normalized',...
            'Parent',hp_SA, 'Units','normalized', 'FontSize',0.825,...
            'Position',[0.725 0.235 0.275 0.1], ...
            'String','corrected sparkFreq:',...
            'TooltipString','corrected spark frequency based on selection criteria for sparks',...
            'ForegroundColor','k');
        
        txt_correctedSpF = uicontrol('Style','text', ...
            'FontUnits','normalized', 'Parent',hp_SA, ...
            'Units','normalized', 'FontSize',0.4,...
            'Position',[0.725 0 0.275 0.225], ...
            'String',{'#';['sp*100',char(956),'m-1*s-1']},...
            'ForegroundColor','r');
        
        % save handles
        hObjs.calcSpParamMethodRBgroup = calcSpParamMethodRBgroup;
        hObjs.rb1Profs = rb1;
        hObjs.rb2Gauss = rb2;
        hObjs.rb3RawImg = rb3;
        
        hObjs.check_showEventsFigs = check_showEventsFigs;
        hObjs.h_bsDet_edit = h_bsDet_edit;

        hObjs.h_pb_sparksAnalysis = h_pb_sparksAnalysis;
        hObjs.txt_correctedSpF = txt_correctedSpF;
        hObjs.check_useNormalizedImg = check_useNormalizedImg;

        
    otherwise % PROFILES
        %%%%%%%%%%%%%%% panel to get profile %%%%%%%%%%%%%%%%%%
        hp_SR = uipanel('Title','get profiles', 'Parent',mainFig,...
            'Units','normalized', 'Position',[0.515 0.01 0.21 0.21],...
            'FontUnits','normalized', 'FontSize',0.1, ...
            'FontWeight','bold');
        
        hp_cSR = uipanel('Title','criteria', 'Parent',hp_SR, ...
            'Units','normalized', 'Position',[0.01 0.01 0.4 0.95], ...
            'FontUnits','normalized',...
            'FontSize',0.1, 'FontAngle','italic');
        
        txt_l = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized', ...
            'Position',[0.01 0.8 0.64 0.2],...
            'String',{'width of ROI:';'(pixels, odd #)'});
        
        h_edit_ROI = uicontrol('Style', 'edit', 'String','11',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position',[0.7 0.8 0.25 0.175], ...
            'Callback',{@profileROI,mainFig});
        
        txt_averageWidth = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position',[0.01 0.55 0.64 0.2], ...
            'String',{'diameter (um)','around spark centre'},...
            'TooltipString','calculate profile only from pixels within diameter around spark centre');
        
        h_edit_averageWidth = uicontrol('Style', 'edit', ...
            'String','1', 'Parent',hp_cSR, ...
            'Units','normalized', ...
            'Position',[0.7 0.55 0.25 0.175],...
            'TooltipString','calculate profile only from pixels within diameter around spark centre',...
            'Callback',{@profileROI,mainFig});
        
        txt_thr_l = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position',[0.01 0.3 0.64 0.2], ...
            'String',{'threshold:';'(#xSD)'});
        
        h_edit_tresh_prof = uicontrol('Style', 'edit', 'String','5',...
            'Parent',hp_cSR, 'Units','normalized', ...
            'Position',[0.7 0.3 0.25 0.175]);
        
        h_smooth_txt = uicontrol('Style','text',...
            'Parent',hp_cSR, 'Units','normalized',...
            'Position',[0.01 0.05 0.64 0.2], ...
            'String',{'span of smoothing:';'(ms)\loess'});
        
        h_smooth_edit = uicontrol('Style','edit', ...
            'String','50', 'Parent',hp_cSR, 'Units','normalized', ...
            'Position',[0.7 0.05 0.25 0.175]);
        
        editArray2 = {h_smooth_edit, h_edit_tresh_prof, ...
            h_edit_averageWidth,h_edit_ROI};
        txtArray2 = {txt_l, txt_averageWidth, txt_thr_l, h_smooth_txt};
        cellfun(@(x) set(x,'FontUnits','normalized', ...
            'FontSize',0.375, 'FontWeight','normal'),txtArray2)
        cellfun(@(x) set(x,'FontUnits','normalized', ...
            'FontSize',0.65, 'FontWeight','normal'),editArray2)
        
        % table of selected profiles
        h_table_profs = uitable('Data',zeros(5,2), ...
            'ColumnEditable',[true false],...
            'ColumnName',{'<HTML> <font size="4"> <b> pos (px) </b> </HTML>', '<HTML> <font size="4"> <b> # events </b> </HTML>'},...
            'ColumnWidth','auto', 'Parent',hp_SR,...
            'Units','normalized', ...
            'Position',[0.425 0.325 0.365 0.575],...
            'FontUnits','normalized', 'FontSize',0.11,...
            'CellEditCallback',{@tableEdit,mainFig});
        
        h_bsDet_txt = uicontrol('Style','text', ...
            'FontUnits','normalized',...
            'Parent',hp_SR, 'Units','normalized', 'FontSize',0.2,...
            'Position',[0.425 0.01 0.25 0.3], ...
            'String',{'baseline detection';'sensitivity';'0-max, 100-min'});
        
        h_bsDet_edit = uicontrol('Style','edit', 'String','75',...
            'FontUnits','normalized', 'FontSize',0.55,...
            'Parent',hp_SR, 'Units','normalized', ...
            'Position',[0.69 0.10 0.1 0.17], ...
            'Callback',{@profileROI,mainFig});
        
        h_pb_profROI = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> draw <br> ROI <html>', ...
            'FontUnits','normalized', 'FontSize',0.3,...
            'Parent',hp_SR, 'Units','normalized', ...
            'Position',[0.8 0.55 0.19 0.35],...
            'Callback',{@profileROI,mainFig});
        
        h_pb_getPosOfProf = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> get <br> position <html>', ...
            'FontUnits','normalized', 'FontSize',0.3,...
            'Parent',hp_SR, 'Units','normalized', ...
            'Position',[0.8 0.1 0.19 0.35],...
            'Callback',{@getPos,mainFig});

        hObjs.h_edit_ROI = h_edit_ROI;
        hObjs.h_edit_averageWidth = h_edit_averageWidth;
        hObjs.h_edit_tresh_prof = h_edit_tresh_prof;
        hObjs.h_smooth_edit = h_smooth_edit;
        
        hObjs.h_pb_profROI = h_pb_profROI;
        hObjs.h_pb_getPosOfProf = h_pb_getPosOfProf;
        
        hObjs.h_table_profs = h_table_profs;
        hObjs.h_bsDet_edit = h_bsDet_edit;
        
        
        %%%%%%%%%%%%%%%% analysis panel for profiles %%%%%%%%%%%%%%%%%%
        hp_Analysis = uipanel('Title','analysis', ...
            'Units','normalized', 'Parent',mainFig, ...
            'Position',[0.73 0.01 0.155 0.21],...
            'FontUnits','normalized', 'FontSize',0.1, ...
            'FontWeight','bold');
        
        check_showEventsFigs = uicontrol('Style', 'checkbox', ...
            'Parent',hp_Analysis,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.8,...
            'String','show individual events', ...
            'Position',[0.01 0.84 0.64 0.1],...
            'Callback',{@analysisOpt,mainFig});
        
        check_sparkParams = uicontrol('Style', 'checkbox', ...
            'Parent',hp_Analysis,...
            'FontUnits','normalized', 'Value',1, ...
            'Units','normalized', 'FontSize',0.8,...
            'String','get sparks params', ...
            'Position',[0.01 0.68 0.64 0.1],...
            'Callback',{@analysisOpt,mainFig});

        check_useNormalizedImg = uicontrol('Style','checkbox', ...
            'Parent',hp_Analysis, 'FontUnits','normalized', ...
            'Value',1, 'Units','normalized', 'FontSize',0.8,...
            'String','use normalized image', ...
            'Position',[0.01 0.53 0.64 0.1],...
            'Callback','');
        
        % method for spark parameters calculation, create two radio buttons in the button group
        calcSpParamMethodRBgroup = uibuttongroup(hp_Analysis, ...
            'Units','normalized',...
            'Title','spark params calc method', ...
            'FontUnits','normalized',...
            'FontSize',0.19, 'FontWeight','bold', 'FontAngle','normal',...
            'Position',[0.01 0.01 0.64 0.4]);
        
        rb1 = uicontrol('Style','radiobutton', ...
            'Parent',calcSpParamMethodRBgroup,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.7,...
            'String','max crossing profiles', ...
            'Position',[0.05 0.5 0.9 0.4]);
        
        rb2 = uicontrol('Style','radiobutton', ...
            'Parent',calcSpParamMethodRBgroup,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.7,...
            'String','2D gaussian fit', ...
            'Position',[0.05 0.05 0.9 0.4], 'Enable','on');
        
        % check_pairAnalysis = uicontrol('Style', 'checkbox', ...
        %     'Parent',hp_Analysis,...
        %     'FontUnits','normalized', 'Value',0, ...
        %     'Units','normalized', 'FontSize',0.8,...
        %     'String','pairwise analysis', ...
        %     'Position',[0.01 0.06 0.64 0.1],...
        %     'Callback','');

        h_pb_sparksAnalysis = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> analyze <br> sparks <html>',...
            'FontUnits','normalized', 'FontSize',0.35, ...
            'Parent',hp_Analysis, 'FontWeight','bold',...
            'Units','normalized', 'Position',[0.675 0.675 0.3 0.3],...
            'Callback',{@detectedSparksAnalysis,mainFig}, ...
            'Enable','on', 'Tag','calcParamsOfEvents');
        
        h_pb_profilesFit = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> fit <br> profiles <html>',...
            'FontUnits','normalized', 'FontSize',0.35, ...
            'FontWeight','normal',...
            'Parent',hp_Analysis, 'Units','normalized', ...
            'Position',[0.675 0.35 0.3 0.3],...
            'Callback',{@profilesFitWindow,mainFig});
        
        h_pb_profileAnalysis = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> analyze <br> profiles <html>',...
            'FontUnits','normalized', 'FontSize',0.35, ...
            'FontWeight','bold',...
            'Parent',hp_Analysis, 'Units','normalized', ...
            'Position',[0.675 0.025 0.3 0.3],...
            'Callback',{@profAnalysis,mainFig});
        
        hObjs.check_showEventsFigs = check_showEventsFigs;
        hObjs.check_sparkParams = check_sparkParams;
        
        hObjs.calcSpParamMethodRBgroup = calcSpParamMethodRBgroup;
        hObjs.rb1Profs = rb1;
        hObjs.rb2Gauss = rb2;
        
        hObjs.check_useNormalizedImg = check_useNormalizedImg;
        
        hObjs.h_pb_sparksAnalysis = h_pb_sparksAnalysis;
        hObjs.h_pb_profilesFit = h_pb_profilesFit;
        hObjs.h_pb_profileAnalysis = h_pb_profileAnalysis;
            
end


%% preview and save pushbutton 
switch analysisType
    case 'spark detection'   
        hp_Analysis = uipanel('Title','save', 'Parent',mainFig,...
            'Units','normalized', ...
            'Position',[0.82 0.01 0.1 0.21],...
            'FontUnits','normalized', 'FontSize',0.1, ...
            'FontWeight','bold');
        h_pb_saveAnalysis = uicontrol('Style', 'pushbutton',...
            'String','save analysis',...
            'FontUnits','normalized', 'FontSize',0.45, ...
            'FontWeight','bold',...
            'Parent',hp_Analysis, 'Units','normalized', ...
            'Position',[0.1 0.75 0.8 0.25],...
            'Callback',{@saveSparkDetAnalysis,mainFig});
        check_saveEventsFigs = uicontrol('Style', 'checkbox', ...
            'Parent',hp_Analysis,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.8,...
            'String','save individual events', ...
            'Position',[0.01 0.625 0.95 0.1]);
        
        uicontrol('Style','text', ...
            'FontUnits','normalized',...
            'Parent',hp_Analysis, 'Units','normalized', ...
            'FontSize',0.8,...
            'Position',[0.01 0.5 0.98 0.1], ...
            'String',{'file format and resolution:'});
        outputFileFormatRBgroup = uibuttongroup(hp_Analysis, ...
            'Units','normalized',...
            'Title','', ...
            'FontUnits','normalized',...
            'FontSize',0.26, 'FontWeight','normal', ...
            'FontAngle','normal',...
            'Position',[0.025 0.35 0.6 0.15]); 
        uicontrol('Style','radiobutton', ...
            'Parent',outputFileFormatRBgroup,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.7,...
            'String','gif', 'Enable','on', ...
            'Position',[0.01 0.01 0.425 0.98]);
        uicontrol('Style','radiobutton', ...
            'Parent',outputFileFormatRBgroup,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.7,...
            'String','pdf', 'Enable','on', ...
            'Position',[0.525 0.01 0.425 0.98]);
        h_edit_res = uicontrol('Style', 'edit', ...
            'String','150', 'Parent',hp_Analysis, ...
            'Units','normalized', 'FontUnits','normalized', ...
            'Position',[0.675 0.35 0.3 0.15], ...
            'Units','normalized', 'FontSize',0.6, ...
            'TooltipString','resolution of output file',...
            'Callback','');

        h_pb_batchAnalysis = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> batch analysis <br/> <i> <span style="font-size:50%">(process multiple images from folder)</span></i> <html>',...
            'FontUnits','normalized', 'FontSize',0.3, ...
            'FontWeight','bold',...
            'Parent',hp_Analysis, 'Units','normalized', ...
            'Position',[0.05 0.025 0.9 0.3],...
            'Callback',{@batchSparkAnalysis,mainFig}, 'Enable','on');
        hObjs.h_pb_saveAnalysis = h_pb_saveAnalysis;
        hObjs.check_saveEventsFigs = check_saveEventsFigs;
        hObjs.h_pb_batchAnalysis = h_pb_batchAnalysis;
        hObjs.outputFileFormatRBgroup = outputFileFormatRBgroup;
        hObjs.h_edit_res = h_edit_res;
        % re-analyze
        h_pb_reAnalyze = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> re-analyze <br/> <i> <span style="font-size:50%">(load image & .xls files)</span></i> <html>',...
            'FontUnits','normalized', 'FontSize',0.3, ...
            'FontWeight','bold',...
            'Parent',mainFig, 'Units','normalized', ...
            'Position',[0.9275 0.15 0.065 0.06],...
            'Callback',{@reAnalyze,mainFig}, 'Enable','on');
        hObjs.h_pb_reAnalyze = h_pb_reAnalyze;

        % output for testing with other software
        uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> save imgs <br/> <i> <span style="font-size:50%">(to test with CaSparks)</span></i> <html>',...
            'FontUnits','normalized', 'FontSize',0.3, ...
            'FontWeight','bold',...
            'Parent',mainFig, 'Units','normalized', ...
            'Position',[0.9275 0.07 0.065 0.06],...
            'Callback',{@imgsOutputForTesting,mainFig}, 'Enable','on');

    otherwise
        hp_Analysis = uipanel('Title','save', 'Parent',mainFig,...
            'Units','normalized', ...
            'Position',[0.89 0.115 0.1 0.105],...
            'FontUnits','normalized', 'FontSize',0.2, 'FontWeight','bold');
        h_pb_saveAnalysis = uicontrol('Style', 'pushbutton',...
            'String','save analysis',...
            'FontUnits','normalized', 'FontSize',0.55, 'FontWeight','bold',...
            'Parent',hp_Analysis, 'Units','normalized', ...
            'Position',[0.1 0.525 0.8 0.475],...
            'Callback',{@saveSparkRecAnalysis,mainFig});
        check_saveEventsFigs = uicontrol('Style', 'checkbox', ...
            'Parent',hp_Analysis,...
            'FontUnits','normalized', 'Value',0, ...
            'Units','normalized', 'FontSize',0.9,...
            'String','save individual events', ...
            'Position',[0.01 0.3 0.95 0.2]);
        check_saveProfsAndFits = uicontrol('Style', 'checkbox', ...
            'Parent',hp_Analysis,...
            'FontUnits','normalized', 'Value',1, ...
            'Units','normalized', 'FontSize',0.9,...
            'String','save profs & fits', ...
            'Position',[0.01 0.01 0.95 0.2]);
        hObjs.h_pb_saveAnalysis = h_pb_saveAnalysis;
        hObjs.check_saveProfsAndFits = check_saveProfsAndFits;
        hObjs.check_saveEventsFigs = check_saveEventsFigs; 
        % re-analyze
        h_pb_reAnalyze = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> re-<br/>analyze <br/> <i> <span style="font-size:65%">(load image & .xls files)</span></i> <html>',...
            'FontUnits','normalized', 'FontSize',0.2, 'FontWeight','bold',...
            'Parent',mainFig, 'Units','normalized', ...
            'Position',[0.89 0.01 0.045 0.09],...
            'Callback',{@reAnalyze,mainFig}, 'Enable','on');
        % data preview button
        h_pb_dataPreview = uicontrol('Style', 'pushbutton',...
            'String','<html> <p align="center"> experiment preview <br/> <i> <span style="font-size:65%">(time series of images)</span></i> <html>',...
            'FontUnits','normalized', 'FontSize',0.16, 'FontWeight','bold',...
            'Parent',mainFig, 'Units','normalized', ...
            'Position',[0.94 0.01 0.045 0.09],...
            'Callback',{@experimentPreviewSparkRecovery,mainFig}, ...
            'Enable','on'); 
        hObjs.h_pb_dataPreview = h_pb_dataPreview;
        hObjs.h_pb_reAnalyze = h_pb_reAnalyze;
end


%%
% save handles of objects
setappdata(mainFig, 'hObjs', hObjs);

end

